DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = airflow_test

TARGETDIRS += ../../platform

all: $(CONTIKI_PROJECT)

UIP_CONF_IPV6=1

CONTIKI = ../../../../contiki
include $(CONTIKI)/Makefile.include
