DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = dw1000_test

TARGETDIRS += ../../platform

USE_DECAWAVE = 1

all: $(CONTIKI_PROJECT)

CONTIKI = ../../../../contiki
include $(CONTIKI)/Makefile.include
