DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = blink

TARGETDIRS += ../../platform

all: $(CONTIKI_PROJECT)

CONTIKI = ../../../../contiki
CONTIKI_WITH_IPV6=1
include $(CONTIKI)/Makefile.include
